module.exports = Object.freeze({
  'en-US': {
    translation: {
      WELCOME: 'Welcome to Fluffy Radio!',
      EXIT: 'OK.. Fluff On!',
      ERROR: 'I wasn\'t able to process your request',
      STREAM_FAILED: 'Looks like we fluffed something up.. The audio stream isn\'t currently available.. Try again later.',
      STREAM_LOOP: 'Don\'t worry. We\'ll always keep looping',
      STREAM_NEXT: 'Sorry, complex algorithms pick the next song.',
      STREAM_PREVIOUS: 'The past is the past, we can\'t go back in time and play old songs.',
      STREAM_REPEAT: 'We\'ll keep fluffing... No need to hit repeat.',
      STREAM_SHUFFLE_ON: 'Wait a minute... we get to pick the fluffing music.',
      STREAM_SHUFFLE_OFF: 'A big bad government agency doesn\'t allow you to turn our shuffle algorithms off.',
      STREAM_START_OVER: 'We can\'t restart the music.',
      STREAM_HELP: 'You\'re screwed!',
    },
  },
  'en-GB': {
    translation: {
      WELCOME: 'Welcome to Fluffy Radio!',
      EXIT: 'OK.. Fluff On!',
      ERROR: 'I wasn\'t able to process your request',
      STREAM_FAILED: 'Looks like we fluffed something up.. The audio stream isn\'t currently available.. Try again later.',
      STREAM_LOOP: 'Don\'t worry. We\'ll always keep looping',
      STREAM_NEXT: 'Sorry, complex algorithms pick the next song.',
      STREAM_PREVIOUS: 'The past is the past, we can\'t go back in time and play old songs.',
      STREAM_REPEAT: 'We\'ll keep fluffing... No need to hit repeat.',
      STREAM_SHUFFLE_ON: 'Wait a minute... we get to pick the fluffing music.',
      STREAM_SHUFFLE_OFF: 'A big bad government agency doesn\'t allow you to turn our shuffle algorithms off.',
      STREAM_START_OVER: 'We can\'t restart the music.',
      STREAM_HELP: '',
    },
  },
  'de-DE': {
    translation: {
      WELCOME: 'Welcome to Fluffy Radio!',
      EXIT: 'OK.. Fluff On!',
      ERROR: 'I wasn\'t able to process your request',
      STREAM_FAILED: 'Looks like we fluffed something up.. The audio stream isn\'t currently available.. Try again later.',
      STREAM_LOOP: 'Don\'t worry. We\'ll always keep looping',
      STREAM_NEXT: 'Sorry, complex algorithms pick the next song.',
      STREAM_PREVIOUS: 'The past is the past, we can\'t go back in time and play old songs.',
      STREAM_REPEAT: 'We\'ll keep fluffing... No need to hit repeat.',
      STREAM_SHUFFLE_ON: 'Wait a minute... we get to pick the fluffing music.',
      STREAM_SHUFFLE_OFF: 'A big bad government agency doesn\'t allow you to turn our shuffle algorithms off.',
      STREAM_START_OVER: 'We can\'t restart the music.',
      STREAM_HELP: '',
    },
  },
});
